### ISSUE TITLE
JDA 3.3.1 Logging compatibility

### ISSUE THREAD

**Issue by MCOfficer** [BtoBastian/sdcf4j#16]
After upgrading to JDA 3.3.1, when one of my commands fails, i get the following error:

    java.lang.NoSuchMethodError: net.dv8tion.jda.core.utils.SimpleLog.log(Ljava/lang/Throwable;)V
	at de.btobastian.sdcf4j.handler.JDA3Handler.invokeMethod(JDA3Handler.java:146)
	at de.btobastian.sdcf4j.handler.JDA3Handler.handleMessageCreate(JDA3Handler.java:128)
	at de.btobastian.sdcf4j.handler.JDA3Handler.access$000(JDA3Handler.java:37)
	at de.btobastian.sdcf4j.handler.JDA3Handler$1.onMessageReceived(JDA3Handler.java:48)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:404)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:980)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:666)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

i suspect this is due to the change from simplelog to slf4j that happened with the update to 3.3.1.
see https://github.com/DV8FromTheWorld/JDA/pull/469 for more.

**Comment by GamingAndStuffs** [comment]
Yep, can confirm line 146 says `SimpleLog.getLog(getClass().getName()).log(e);`, but should be changed to a slf4j logger like in the JavacordHandler, with 
`Logger logger = LoggerFactory.getLogger(name); 
logger.error("blah blah blah", e);`

**Comment by BtoBastian** [comment]
Hey,

version 1.0.6 should fix this issue :)

**Comment by MCOfficer** [comment]
can confirm, logging is back to normal. thank you very much ^^
