### ISSUE TITLE
JDA 3.3.1 logging compatibility, round 2

### ISSUE THREAD

**Issue by MCOfficer** [BtoBastian/sdcf4j#21]
with version 3.3.1_304, JDA has ultimately switched to SLF4J for logging.
with this and any higher versions, the error logger throws the following error:

```
01:38:10.805 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.core.JDA - One of the EventListeners had an uncaught exception
java.lang.NoClassDefFoundError: net/dv8tion/jda/core/utils/SimpleLog
	at de.btobastian.sdcf4j.handler.JDA3Handler.invokeMethod(JDA3Handler.java:143)
	at de.btobastian.sdcf4j.handler.JDA3Handler.handleMessageCreate(JDA3Handler.java:125)
	at de.btobastian.sdcf4j.handler.JDA3Handler.access$000(JDA3Handler.java:37)
	at de.btobastian.sdcf4j.handler.JDA3Handler$1.onMessageReceived(JDA3Handler.java:48)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:405)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:1011)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:687)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1059)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.core.utils.SimpleLog
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 common frames omitted
```

Relevant: https://github.com/DV8FromTheWorld/JDA/commit/e9399b7beff67542b7ca42e202d3f9ce01ead9b8

**Comment by BtoBastian** [comment]
Version `v.1.0.8` is already compatible with the latest version of JDA.

**Comment by MCOfficer** [comment]
oh, i missed a version! my bad for not checking that
