### ISSUE TITLE
[JDA3] switch to non-deprecated methods

### ISSUE THREAD

**Issue by MCOfficer** [BtoBastian/sdcf4j#35]
`Message#getContentRaw` and `Message#getContent` are deprecated with 3.4.0 and have been removed with 3.5.0, in favour of `getRawContent` and `getContentDisplay`. With 3.5.0, sdcf4j throws the following error when receiving a message:
```
java.lang.NoSuchMethodError: net.dv8tion.jda.core.entities.Message.getRawContent()Ljava/lang/String;
	at de.btobastian.sdcf4j.handler.JDA3Handler.handleMessageCreate(JDA3Handler.java:91)
	at de.btobastian.sdcf4j.handler.JDA3Handler.access$000(JDA3Handler.java:39)
	at de.btobastian.sdcf4j.handler.JDA3Handler$1.onMessageReceived(JDA3Handler.java:55)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:403)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:1006)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:680)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1054)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by BtoBastian** [comment]
Version `v1.0.9` uses the latest JDA version
